var dir_edd90973441a00c42f34265876a42548 =
[
    [ "auxapi.c", "auxapi_8c.html", "auxapi_8c" ],
    [ "balance.c", "balance_8c.html", "balance_8c" ],
    [ "coarsen.c", "coarsen_8c.html", "coarsen_8c" ],
    [ "contig.c", "contig_8c.html", "contig_8c" ],
    [ "defs.h", "defs_8h_source.html", null ],
    [ "fm.c", "fm_8c.html", "fm_8c" ],
    [ "gklib.c", "gklib_8c.html", "gklib_8c" ],
    [ "gklib_defs.h", "gklib__defs_8h.html", "gklib__defs_8h" ],
    [ "gklib_rename.h", "gklib__rename_8h.html", "gklib__rename_8h" ],
    [ "graph.c", "libmetis_2graph_8c.html", "libmetis_2graph_8c" ],
    [ "kmetis.c", "kmetis_8c.html", "kmetis_8c" ],
    [ "kwayfm.c", "kwayfm_8c.html", "kwayfm_8c" ],
    [ "kwayrefine.c", "kwayrefine_8c.html", "kwayrefine_8c" ],
    [ "macros.h", "macros_8h_source.html", null ],
    [ "metislib.h", "metislib_8h_source.html", null ],
    [ "minconn.c", "minconn_8c.html", "minconn_8c" ],
    [ "options.c", "options_8c.html", "options_8c" ],
    [ "pmetis.c", "pmetis_8c.html", "pmetis_8c" ],
    [ "proto.h", "proto_8h_source.html", null ],
    [ "rename.h", "rename_8h_source.html", null ],
    [ "stdheaders.h", "stdheaders_8h_source.html", null ],
    [ "struct.h", "struct_8h_source.html", null ],
    [ "wspace.c", "wspace_8c.html", "wspace_8c" ]
];