var namespacesofa_1_1helper_1_1logging_1_1countingmessagehandler =
[
    [ "CountingMessageHandler", "classsofa_1_1helper_1_1logging_1_1countingmessagehandler_1_1_counting_message_handler.html", "classsofa_1_1helper_1_1logging_1_1countingmessagehandler_1_1_counting_message_handler" ],
    [ "MainCountingMessageHandler", "classsofa_1_1helper_1_1logging_1_1countingmessagehandler_1_1_main_counting_message_handler.html", "classsofa_1_1helper_1_1logging_1_1countingmessagehandler_1_1_main_counting_message_handler" ]
];