var namespacesofa_1_1helper_1_1logging =
[
    [ "countingmessagehandler", "namespacesofa_1_1helper_1_1logging_1_1countingmessagehandler.html", "namespacesofa_1_1helper_1_1logging_1_1countingmessagehandler" ],
    [ "loggingmessagehandler", "namespacesofa_1_1helper_1_1logging_1_1loggingmessagehandler.html", "namespacesofa_1_1helper_1_1logging_1_1loggingmessagehandler" ],
    [ "percomponentloggingmessagehandler", "namespacesofa_1_1helper_1_1logging_1_1percomponentloggingmessagehandler.html", "namespacesofa_1_1helper_1_1logging_1_1percomponentloggingmessagehandler" ],
    [ "routingmessagehandler", "namespacesofa_1_1helper_1_1logging_1_1routingmessagehandler.html", "namespacesofa_1_1helper_1_1logging_1_1routingmessagehandler" ],
    [ "ClangMessageHandler", "classsofa_1_1helper_1_1logging_1_1_clang_message_handler.html", "classsofa_1_1helper_1_1logging_1_1_clang_message_handler" ],
    [ "ClangStyleMessageFormatter", "classsofa_1_1helper_1_1logging_1_1_clang_style_message_formatter.html", "classsofa_1_1helper_1_1logging_1_1_clang_style_message_formatter" ],
    [ "ComponentInfo", "structsofa_1_1helper_1_1logging_1_1_component_info.html", "structsofa_1_1helper_1_1logging_1_1_component_info" ],
    [ "ConsoleMessageHandler", "classsofa_1_1helper_1_1logging_1_1_console_message_handler.html", "classsofa_1_1helper_1_1logging_1_1_console_message_handler" ],
    [ "DefaultStyleMessageFormatter", "classsofa_1_1helper_1_1logging_1_1_default_style_message_formatter.html", "classsofa_1_1helper_1_1logging_1_1_default_style_message_formatter" ],
    [ "ExceptionMessageHandler", "classsofa_1_1helper_1_1logging_1_1_exception_message_handler.html", "classsofa_1_1helper_1_1logging_1_1_exception_message_handler" ],
    [ "FileInfo", "structsofa_1_1helper_1_1logging_1_1_file_info.html", "structsofa_1_1helper_1_1logging_1_1_file_info" ],
    [ "FileInfoOwningFilename", "structsofa_1_1helper_1_1logging_1_1_file_info_owning_filename.html", "structsofa_1_1helper_1_1logging_1_1_file_info_owning_filename" ],
    [ "FileMessageHandler", "classsofa_1_1helper_1_1logging_1_1_file_message_handler.html", "classsofa_1_1helper_1_1logging_1_1_file_message_handler" ],
    [ "MainConsoleMessageHandler", "classsofa_1_1helper_1_1logging_1_1_main_console_message_handler.html", null ],
    [ "Message", "classsofa_1_1helper_1_1logging_1_1_message.html", "classsofa_1_1helper_1_1logging_1_1_message" ],
    [ "MessageDispatcher", "classsofa_1_1helper_1_1logging_1_1_message_dispatcher.html", "classsofa_1_1helper_1_1logging_1_1_message_dispatcher" ],
    [ "MessageDispatcherImpl", "classsofa_1_1helper_1_1logging_1_1_message_dispatcher_impl.html", "classsofa_1_1helper_1_1logging_1_1_message_dispatcher_impl" ],
    [ "MessageFormatter", "classsofa_1_1helper_1_1logging_1_1_message_formatter.html", "classsofa_1_1helper_1_1logging_1_1_message_formatter" ],
    [ "MessageHandler", "classsofa_1_1helper_1_1logging_1_1_message_handler.html", "classsofa_1_1helper_1_1logging_1_1_message_handler" ],
    [ "RichConsoleStyleMessageFormatter", "classsofa_1_1helper_1_1logging_1_1_rich_console_style_message_formatter.html", "classsofa_1_1helper_1_1logging_1_1_rich_console_style_message_formatter" ],
    [ "SilentMessageHandler", "classsofa_1_1helper_1_1logging_1_1_silent_message_handler.html", "classsofa_1_1helper_1_1logging_1_1_silent_message_handler" ],
    [ "SofaComponentInfo", "classsofa_1_1helper_1_1logging_1_1_sofa_component_info.html", "classsofa_1_1helper_1_1logging_1_1_sofa_component_info" ]
];